### ISSUE TITLE
java-microprofile: Remove ~ mounts as Codewind now supports init outside the PFE container

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#363] opened 2019-09-18 15:29 UTC
We were mounting ~/.m2 folder for appsody to work with Codewind. However, that meant we could not longer use APPSODY_DEPS and were at risk of mixing dependencies from within the container and host.

We would like to change this behaviour now as CodeWind can initialize projects outside of the container and we might not need this fix any more.

The idea would be to update this stack, and test it with updated codewind to confirm this works before we get all stacks updated and released.

Codewind team will document how to handle users who are not on latest codewind (perhaps as troubleshooting doc)

**Comment by ebullient** [comment] 2019-09-24 15:01
The spring stack _does_ use ~ mounts to share the .m2 cache, however. For Java projects, sharing the .m2 cache is typical (using DEP volumes is not). I don't think APPSODY_DEPS is appropriate for Java projects, which is why I didn't go there to begin with.

**Comment by ebullient** [comment] 2019-11-06 14:50
This will not work, and will break expected behavior: you need a parent pom to enforce behavior, and unless the home .m2 directory is shared, you break existing maven IDE tools.

So the question is whether or not we really want to get into a position where we require appsody for all interactions with these projects such that they don't work w/ existing tools (a barrier to adoption in my view).

**Comment by ebullient** [comment] 2019-11-06 14:55
https://github.com/eclipse/codewind/issues/583 -- related

**Comment by awisniew90** [comment] 2019-12-12 16:20
Do we have a todo for this issue? Seems that for Java projects, we are OK mounting the ~/.m2 repo since this is a typical practice.  If I'm understanding the latest concern in eclipse/codewind#583, both Codewind and Appsody will be detecting changes and running maven builds, potentially colliding in ~/.m2.  @ebullient, as you pointed out though, most on_change actions in appsody aren't writing back to ~/.m2. Even still, a better solution would be to have Codewind NOT detect changes and just let Appsody handle that.  Is that correct? If so, can we close this issue, or is there more to do?

**Comment by ebullient** [comment] 2019-12-12 18:16
One way or the other. EITHER the IDE detects changes OR Appsody does. If codewind is launching appsody, it can use a command-line option to disable the watcher, and allow the IDE to perform operations when changes are detected as it usually would.

**Comment by awisniew90** [comment] 2019-12-12 18:30
Gotcha - I think we can close this issue then. I don't believe there are any changes needed for this.

**Closed by awisniew90** 2019-12-12 18:30 UTC
Labels: enhancement, stack/java-microprofile
