### ISSUE TITLE
Quarkus: application not updated on source file change (in Codewind)

### ISSUE THREAD

**Issue by makandre** [appsody/stacks#753] opened 2020-04-10 01:22 UTC
**Describe the bug**

When using the Quarkus stack in Codewind, a source file change is not triggering the application to get updated

I was not able to reproduce this outside of Codewind, however, what I can determine is the source file change **does** get reflected inside the appsody container, and it does trigger something to happen:

```
[Container] [ERROR] Port 5005 in use, not starting in debug mode
[Container] Debugger failed to attach: handshake failed - connection prematurally closed
[Container] 2020-04-10 01:04:35,887 INFO  [io.quarkus] (Quarkus Shutdown Thread) Quarkus stopped in 0.002s
```

Additionally, if I shell into the appsody container and make changes directly inside, it does trigger the application update normally. 

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using (including the version):

**Screenshots**

**Additional context**

**Comment by neeraj-laad** [comment] 2020-04-14 08:44
@paulrobinson ^^

**Comment by paulrobinson** [comment] 2020-04-15 11:56
Thanks @neeraj-laad  and @makandre.

Are you saying that you make a change to the source code in Codewind, and then you can see that specific change reflected on the filesystem when you shell into the container, but Quarkus doesn't react to that change? 

If so, I'm confused why shelling into the container direct to make the code change would cause Quarkus to reload the code. 

I'm just trying to understand at what point in the flow it's breaking. 

I can probably have a go at reproducing this later this week (Friday). Can you provide some reproduction steps for someone unfamiliar with Codewind? Or maybe I just: install Codewind into VSCode, select a new Quarkus application, run it, change code, observe code change not reflected in Quarkus.

**Comment by skoh7645** [comment] 2020-04-15 12:12
@paulrobinson Yes, the steps to reproduce this in Codewind are exactly as you have said. 

When you save a file change, the change is not reflected in the webpage during hot reload. You have to do a full build again (rerun `appsody run`) to see the application updated

**Comment by groeges** [comment] 2020-04-15 12:14
Hi Paul, the steps you stated are the easiest way to reproduce and how I did it yesterday.

When I tried this and modified the GreetingResource.java code Quarkus from within Codewind, the logs in the running Quarkus container showed this:
```
2020-04-14 16:51:32,808 INFO  [io.quarkus] (Quarkus Shutdown Thread) Quarkus stopped in 0.002s
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-04-14 16:51:37,574 INFO  [io.quarkus] (main) getting-started 1.0-SNAPSHOT (powered by Quarkus 1.3.0.Final) started in 1.912s. Listening on: http://0.0.0.0:8080
2020-04-14 16:51:37,577 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-04-14 16:51:37,577 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```
notice the first line that is saying it is using [io.quarkus] (Quarkus Shutdown Thread) and it doesnt detect the file change and rebuild the app.

What is supposed to be doing the watching for code changes, is this Quarkus itself?

However, if I exec into the Quarkus container and look at the file I changed from Codewind, it has been updated to what was changed from within Codewind.  While within the container I edit the same file and save it I get the following:

```
2020-04-14 16:49:43,588 INFO  [io.qua.dev] (vert.x-worker-thread-7) Changed source files detected, recompiling [/project/user-app/src/main/java/org/acme/quickstart/GreetingResource.java]
2020-04-14 16:49:44,352 INFO  [io.quarkus] (vert.x-worker-thread-7) Quarkus stopped in 0.025s
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-04-14 16:49:44,701 INFO  [io.quarkus] (vert.x-worker-thread-7) getting-started 1.0-SNAPSHOT (powered by Quarkus 1.3.0.Final) started in 0.074s. Listening on: http://0.0.0.0:8080
2020-04-14 16:49:44,701 INFO  [io.quarkus] (vert.x-worker-thread-7) Profile dev activated. Live Coding activated.
2020-04-14 16:49:44,702 INFO  [io.quarkus] (vert.x-worker-thread-7) Installed features: [cdi, resteasy]
2020-04-14 16:49:44,702 INFO  [io.qua.dev] (vert.x-worker-thread-7) Hot replace total time: 1.130s 
```
which seems to have detected the change and recompiled the application. 

So main question is why is one different from the other?

**Comment by matejvasek** [comment] 2020-04-15 15:13
@skoh7645 does the codewind software contain appsody in itself? If so, is what version? The quarkus stack employs quite new feature: multiple deps mounts. I think that may be causing issues.
```
[{volume appsody-controller-0.3.4 /var/lib/docker/volumes/appsody-controller-0.3.4/_data /.appsody local z true }
 {bind  /home/mvasek/codewind-data/my-java-quarkus /project/user-app   true rprivate}
 {volume my-java-quarkus-deps /var/lib/docker/volumes/my-java-quarkus-deps/_data /project/user-app/target;/home/quarkus/.m2 local z true }]
```
Note that `/project/user-app/target;/home/quarkus/.m2`.

**Comment by makandre** [comment] 2020-04-15 15:26
@matejvasek Yes Codewind does bundle appsody with it.  We saw this in Codewind dev branch using the latest `0.6.0` release of appsody

**Comment by skoh7645** [comment] 2020-04-15 15:33
@matejvasek We did notice that currently Codewind `0.9.0` is using Appsody `0.5.8` with the `0.3.0` Quarkus stack (this stack requires at least Appsody `0.6.0`). However, when we used an older version of the Quarkus (which does not require the latest Appsody version) we still saw this issue. We do not think it is a problem with the Appsody CLI version as older versions of the Quarkus stack shows the same issue when using Codewind.

**Comment by matejvasek** [comment] 2020-04-15 16:18
What does `docker inspect -f '{{ .Mounts }}' PROCID` return?

**Comment by groeges** [comment] 2020-04-15 16:48
In my running container stared by codewind I have:
```
[
    {bind  /Users/stevengroeger/codewind-data/test-quarkus /project/user-app   true rprivate
    } {volume appsody-test-quarkus-20200415154851.61601840 /var/lib/docker/volumes/appsody-test-quarkus-20200415154851.61601840/_data /project/user-app/target local z true
    } {volume appsody-test-quarkus-20200415154851.61635870 /var/lib/docker/volumes/appsody-test-quarkus-20200415154851.61635870/_data /home/quarkus/.m2 local z true
    } {volume appsody-controller-0.3.4 /var/lib/docker/volumes/appsody-controller-0.3.4/_data /.appsody local z true
    }
]
```

**Comment by groeges** [comment] 2020-04-15 18:10
I have noticed one difference between running this locally and within codewind. 

When running locally the bind mount for `/project/user-app` within the container is to the project directory, so in my case it is `/Users/stevengroeger/projects/test-quarkus`. 

Whereas with codewind, even though my project was specified to be created in the `/Users/stevengroeger/projects/test-quarkus` directory, Codewind seems to copy the project code to `/Users/stevengroeger/codewind-data/test-quarkus` (which is hidden from the user) and  the container has the bind mount to this directory. 

So with the latter, when the code is changed in the project directory, Codewind copies the changed files to the codewind-data directory. The container should pickup those changes and the quarkus hot replace should get triggered, but for some reason when this happens the container gets the changed file but quarkus ends up doing "[io.quarkus] (Quarkus Shutdown Thread) Quarkus stopped"

**Comment by matejvasek** [comment] 2020-04-15 18:15
When running `watch -n 0.1 docker exec -ti PROCID lsof -i :8080,5005` I noticed that `appsody run` doesn't kill the java process (the same pid is displayed), but with `codewind` it seems that the process is restarted when code is changed.

**Comment by paulrobinson** [comment] 2020-04-15 18:20
Ah yes, I meant to say. I noticed the following in the original report:

```[Container] [ERROR] Port 5005 in use, not starting in debug mode```

Which suggests that multiple versions of Quarkus could be running.

**Comment by matejvasek** [comment] 2020-04-15 18:47
When I manually copy java file from project to the `codewind-data` directory the code his hot swapped. What else is `codewind` doing beside copying files when a change is detected?

**Comment by makandre** [comment] 2020-04-15 18:58
Just FYI, this is where Codewind does the writing out of files: https://github.com/eclipse/codewind/blob/master/src/pfe/portal/routes/projects/bind.route.js#L173

**Comment by matejvasek** [comment] 2020-04-15 19:20
Looks like quarkus doesn't like modification of `pom.xml` while `mvn quarkus:dev`.

**Comment by matejvasek** [comment] 2020-04-15 19:28
I think this could be possibly fixed by selective updating, I mean upload/update only files that has been really changed.

**Comment by makandre** [comment] 2020-04-15 19:32
@matejvasek So are you saying that when you change `GreetingResource.java`, you see the `pom.xml` file is also getting uploaded? That's actually strange...

**Comment by matejvasek** [comment] 2020-04-15 19:32
Let me check.

**Comment by matejvasek** [comment] 2020-04-15 19:37
When I changed just the GreetingResource.java file then pom.xml was also updated in the `codewind-data`. Checked by `watch -n 0.1 stat pom.xml`

**Comment by matejvasek** [comment] 2020-04-15 19:43
Of course ideally quarkus should survive changes of pom.xml too.

**Comment by makandre** [comment] 2020-04-15 19:53
Thanks for confirming that @matejvasek.  We'll take a look on Codewind side why we seem to be uploading the pom file when it's unchagned.

**Comment by groeges** [comment] 2020-04-16 08:12
I can also confirm that if I change the GreetingResource.java in my project directory, that file gets updated in the codewind-data directory as well as the pom.xml, but the pom.xml does not get updated in the project directory.

I can also confirm that when running the quarkus stack with `appsody run` (not using codewind) and I modify the pom.xml, then the stack crashes and restarts same as when running under codewind. 

So we have 2 issues here:
1: quarkus stack doesn't handle hot replace of `pom.xml`
2: codewind updates pom.xml even if it hasn't changed when other files are changed.

If #2 was fixed then I think that the hot replace for quarkus would work 95% of the time. It could be documented that modifying pom.xml will need a rebuild/restart of the container (until the quarkus stack can handle hot replace of pom.xml)

**Comment by makandre** [comment] 2020-04-16 11:30
There could be some reason Codewind is copying the pom (tho I can't imagine why at the moment).  I'll check with the team and work through that in https://github.com/eclipse/codewind/issues/2657

**Comment by makandre** [comment] 2020-04-16 13:09
Ok, I found a potential fix for the pom issue in Codewind, see https://github.com/eclipse/codewind/issues/2657#issuecomment-614635378

Basically, the pom was not uploaded everytime, but it was in temp staging dir in PFE and the project is copied to `codewind-data` when any file change and upload occurs.

**Comment by makandre** [comment] 2020-04-16 15:29
We have put in a fix on Codewind side to preserve the pom timestamp, and that appears to make Quarkus happy.

**Comment by paulrobinson** [comment] 2020-04-16 17:27
Good news :-)

Do you still see a problem in that "Quarkus stack doesn't handle hot replace of pom.xml"? If so, I can take a look.

**Comment by makandre** [comment] 2020-04-16 19:32
Yes, if I modify the pom directly it will crash

**Comment by paulrobinson** [comment] 2020-04-17 15:49
@makandre when you say it 'crashes', do you mean it restarts the full server? Other than looking odd, do you experience any problems?

I believe this behaviour is intentional for Quarkus. Given how quickly Quarkus boots we are quite aggressive about how much is restarted on code changes. It's also simpler and safer to do fuller restarts.

I created a simple application from https://code.quarkus.io/ (without Appsody, to help isolate the behaviour), then ran it with: `./mvnw compile quarkus:dev`

You will see:

```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-04-17 16:24:18,862 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT (powered by Quarkus 1.3.2.Final) started in 0.749s. Listening on: http://0.0.0.0:8080
2020-04-17 16:24:18,873 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-04-17 16:24:18,873 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```

I then did a `touch pom.xml` to simulate a code change of the pom.xml. You will notice the following, which shows a full reload of the server. I think this is expected for pom.xml changes as there's a lot that can change in there (e.g new dependencies). 

```
[ERROR] Port 5005 in use, not starting in debug mode
Debugger failed to attach: handshake failed - connection prematurally closed
2020-04-17 16:24:59,820 INFO  [io.quarkus] (Quarkus Shutdown Thread) Quarkus stopped in 0.002s
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-04-17 16:25:01,908 INFO  [io.quarkus] (main) code-with-quarkus 1.0.0-SNAPSHOT (powered by Quarkus 1.3.2.Final) started in 0.698s. Listening on: http://0.0.0.0:8080
2020-04-17 16:25:01,909 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2020-04-17 16:25:01,910 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
```

I then did a `touch src/main/java/org/acme/ExampleResource.java` to simulate a Java code change, and visited http://0.0.0.0:8080/ (source code changes are live reloaded on request). This resulted in the following hot replace. I'm not sure how much of the server was restarted this time (maybe less than when the pom.xml changed):  

```
2020-04-17 16:26:34,005 INFO  [io.qua.dev] (vert.x-worker-thread-0) Changed source files detected, recompiling [/Users/paul/tmp/quarkus/code-with-quarkus/src/main/java/org/acme/ExampleResource.java]
system modules path not set in conjunction with -source 11, line -1 in [unknown source]2020-04-17 16:26:34,294 INFO  [io.quarkus] (vert.x-worker-thread-0) Quarkus stopped in 0.012s
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-04-17 16:26:34,427 INFO  [io.quarkus] (vert.x-worker-thread-0) code-with-quarkus 1.0.0-SNAPSHOT (powered by Quarkus 1.3.2.Final) started in 0.020s. Listening on: http://0.0.0.0:8080
2020-04-17 16:26:34,427 INFO  [io.quarkus] (vert.x-worker-thread-0) Profile dev activated. Live Coding activated.
2020-04-17 16:26:34,427 INFO  [io.quarkus] (vert.x-worker-thread-0) Installed features: [cdi, resteasy]
2020-04-17 16:26:34,428 INFO  [io.qua.dev] (vert.x-worker-thread-0) Hot replace total time: 0.423s
```

This all looks right to me, except the `[ERROR] Port 5005 in use, not starting in debug mode` message after touching the `pom.xml` which seems a bit odd. However, that occurs before the shutdown occurs, not on the new startup.

I tested that the debugger port is available after the restart, and it is. I was able to use the debugger. However, I did need to re-connect the debugger which might be a bit irritating. Although, the debugger does stay attached when a Java code change is live-reloaded.

**Comment by makandre** [comment] 2020-04-17 16:09
Hey @paulrobinson, yes that is exactly what I see.

I guess it is that ERROR message that made me think it crashed (and also the error appears on every other edit of the pom file)

```
[Container] [ERROR] Port 5005 in use, not starting in debug mode
[Container] Debugger failed to attach: handshake failed - connection prematurally closed
```

**Comment by matejvasek** [comment] 2020-04-17 16:13
@paulrobinson I think the problem is when pom.xml and some java source is updated simultaneously.
The restart itself isn't probably bad thing, but it looks like it causing quarkus to miss that java source has been changed too. However I doubt that simultaneous update of pom.xml and java src happens often in practice.

**Comment by paulrobinson** [comment] 2020-04-17 16:39
Aha! I think I reproduced with:

```
gsed -i 's/YYY/ZZZ/g' ./src/main/java/org/acme/quickstart/GreetingResource.java; touch pom.xml
```
I then visited http://0.0.0.0:8080/hello and 'YYY' was returned, despite the code looking like:

```
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "ZZZ";
    }
```

I refresh http://0.0.0.0:8080/hello over and over, and I still get YYY. After I touch `src/main/java/org/acme/quickstart/GreetingResource.java` the code does reload.

So looks like we've found an edge-case where live code reload doesn't work. I'll probably file a Quarkus issue shortly (I need to finish for the day now).

**Comment by groeges** [comment] 2020-06-04 12:09
@paulrobinson Did you raise a Quarkus issue for this live core reload issue?
If so, can you link the issue here so we can track it and retest this issue once it has been resolved. 
Thanks

**Comment by paulrobinson** [comment] 2020-06-04 14:37
@groeges Sorry, I never actually got around to reporting the issue. However, it seems fixed in Quarkus 1.5.0.Final. I've just tried to reproduce it now, and I can't.

Can you verify with your scenario?

**Comment by groeges** [comment] 2020-06-08 11:59
@paulrobinson Thanks. I retested this issue with the latest version of Codewind and Quarkus stack and everything seems to be working OK now. Will close this issue.

**Closed by groeges** 2020-06-08 11:59 UTC
Labels: bug, external/codewind, stack/quarkus

**Comment by paulrobinson** [comment] 2020-06-08 12:32
Thanks, good to know!
