### ISSUE TITLE
files owned by root when running appsody on linux

### ISSUE THREAD

**Issue by tnixa** [appsody/stacks#550] opened 2019-12-09 21:40 UTC
**Describe the bug**
I was running my BATS integration tests against all the incubator stacks and at the end it tries to remove all the temporary directories and I was getting some permission denied errors on the nodejs-loopback and python-flask projects...
```
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/python-flask/__pycache__/__init__.cpython-37.pyc': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/__tests__/acceptance/ping.controller.acceptance.js.map': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/__tests__/acceptance/home-page.acceptance.d.ts': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/__tests__/acceptance/test-helper.js.map': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/__tests__/acceptance/test-helper.js': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/__tests__/acceptance/ping.controller.acceptance.d.ts': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/__tests__/acceptance/home-page.acceptance.js': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/__tests__/acceptance/test-helper.d.ts': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/__tests__/acceptance/home-page.acceptance.js.map': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/__tests__/acceptance/ping.controller.acceptance.js': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/application.js': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/index.js.map': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/migrate.d.ts': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/sequence.js.map': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/application.d.ts': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/index.d.ts': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/index.js': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/controllers/ping.controller.js': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/controllers/index.js.map': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/controllers/ping.controller.js.map': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/controllers/index.d.ts': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/controllers/index.js': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/controllers/ping.controller.d.ts': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/migrate.js': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/sequence.d.ts': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/sequence.js': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/application.js.map': Permission denied
   rm: cannot remove '/home/tnixa/bats_temp/temp/src/github.com/appsody/nodejs-loopback/dist/migrate.js.map': Permission denied
```
I investigated this with @chilanti and we believe this is due to docker running as `root` on linux as this problem does not happen on mac or windows.
A possible workaround is to run docker with `-u <id number>` ...
```
[tnixa@oc3753264574 loopback]$ id -u
1000
[tnixa@oc3753264574 loopback]$ docker run --rm -it -v /home/tnixa:/tmp -u 1000 ubuntu touch /tmp/test.txt
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
7ddbc47eeb70: Already exists 
c1bbdc448b72: Already exists 
8c3b70e39044: Already exists 
45d437916d57: Already exists 
Digest: sha256:6e9f67fa63b0323e9a1e587fd71c561ba48a034504fb804fd26fd8800039835d
Status: Downloaded newer image for ubuntu:latest
[tnixa@oc3753264574 loopback]$ ls -la /home/tnixa/test.txt 
-rw-r--r--. 1 tnixa root 0 Dec  9 15:30 /home/tnixa/test.txt
```

Without the `-u` the file is owned by `root`...
```
[tnixa@oc3753264574 loopback]$ id -u
1000
[tnixa@oc3753264574 loopback]$ docker run --rm -it -v /home/tnixa:/tmp -u 1000 ubuntu touch /tmp/test.txt
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
7ddbc47eeb70: Already exists 
c1bbdc448b72: Already exists 
8c3b70e39044: Already exists 
45d437916d57: Already exists 
Digest: sha256:6e9f67fa63b0323e9a1e587fd71c561ba48a034504fb804fd26fd8800039835d
Status: Downloaded newer image for ubuntu:latest
[tnixa@oc3753264574 loopback]$ ls -la /home/tnixa/test.txt 
-rw-r--r--. 1 tnixa root 0 Dec  9 15:30 /home/tnixa/test.txt
```

Our appsody instructions for linux OS have the user adding their local user to the `docker` group which was our solution to work-around this root ownership issue but further changes may need to be made

**To Reproduce**
(From LINUX OS)
1. `mkdir nodejs-loopback`
2. `cd nodejs-loopback`
3. `appsody init nodejs-loopback`
4. `appsody run`
5. `appsody stop --name nodejs-loopback-dev`
6. `ls -la dist\` to see files owned by root

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] RHEL 7.7

**If applicable please specify:**
 - CLI version: 0.5.2
 - Stack you are using (including the version): nodejs-loopback

I'd like to get comments from @neeraj-laad on this issue...

**Comment by sam-github** [comment] 2019-12-09 21:45
These are all related:
- https://github.com/appsody/stacks/issues/530
- https://github.com/appsody/stacks/issues/518

**Comment by sam-github** [comment] 2019-12-13 00:54
https://github.com/appsody/stacks/issues/518#issuecomment-565157560 might describe the root cause, and should have enough information to see if this python issue is also related to the mounting of the deps volume.

**Comment by Kamran64** [comment] 2020-01-23 14:28
Closing this issue: Python flask was handled in https://github.com/appsody/stacks/pull/579. As for loopback we'll use https://github.com/appsody/stacks/issues/518 to track as this applies to all node stacks and #518 has more context.

**Closed by Kamran64** 2020-01-23 14:28 UTC
