### ISSUE TITLE
nodejs-express scaffold on linux: test fails: Your configured registry (https://registry.npmjs.org/) may not support audit requests

### ISSUE THREAD

**Issue by tnixa** [appsody/stacks#623] opened 2020-01-24 20:13 UTC
**Describe the bug**
Running BATS integration test with the latest stack and cli code via Jenkins to Ubuntu and RHEL VMs and both are failing on stack validate during the run and test steps on the nodejs-express stack scaffold template with...
```
[Container] [?25l[[7m         [27m[90m.........[0m] - prepare:user-app: [32;40mtiming[0m [35maudit body[0m Completed in 1ms[0m[K

[K[?25h[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m ENOAUDIT
[Container] [0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35maudit[0m Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.
[Container] [0m
[Container] [37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[Container] [0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /root/.npm/_logs/2020-01-24T17_39_59_955Z-debug.log
[Container] [0m[Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1
```
Full log is here: 
[integration-good-path-appsody-stack-validate-nodejs-express.log](https://github.com/appsody/stacks/files/4110454/integration-good-path-appsody-stack-validate-nodejs-express.log)

**To Reproduce**
1. Go to `stacks/incubator/nodejs-express`
2. `appsody stack validate`

**Environment Details (please complete the following information):**
OS: [e.g. iOS] Ubuntu 18.0.4 and RHEL 7.7
If applicable please specify:

**CLI version: latest dev**
Stack you are using (including the version): nodejs-express

**Comment by sam-github** [comment] 2020-01-24 21:54
I'll look into it. You aren't using a private registry, are you? Perhaps not even inadvertently, because you are in IBM infrastructure?

There are also rumours this might have been fixed by an npm update,  or sometimes caused by bad cached npm output.

**Comment by tnixa** [comment] 2020-01-24 22:24
I'm running in the IBM intranet on FYRE VMs. Not intentionally using a private registry.

**Comment by andrewhughes101** [comment] 2020-03-16 17:14
This seems to be an NPM issue that could be for a few reasons. It doesnt look like there's anythibng that can be done from the appsody point of view. We could maybe update npm to the latest version but otherwise I dont think there's anything else that can be done.

@sam-github do you want to add anything or do you think this should be closed?

Additional refs:
- https://npm.community/t/enoaudit-from-registry-npmjs-org-503/4642/56
- https://status.npmjs.org/incidents/1jdmllbx0q59
- https://npm.community/t/running-npm-audit-gives-503-enoaudit-error/5543

**Comment by sam-github** [comment] 2020-03-16 17:17
Closing, but @tnixa, if it resurfaces again, please reopen.

**Closed by sam-github** 2020-03-16 17:17 UTC
Labels: bug, stack/nodejs-express
