### ISSUE TITLE
generate new index.yaml from travis build

### ISSUE THREAD

**Issue by mhamwala** [appsody/stacks#98] opened 2019-07-18 10:34 UTC
**Is your feature request related to a problem? Please describe.**
Currently, we are releasing each stack manually. Prone to human error and a lot of churn.

**Describe the solution you'd like**
Using https://github.com/appsody/stacks/issues/96 we should generate the index.yaml from the stack and update it with the latest release of tars and images

**Describe alternatives you've considered**
This process might change once we decide where we are going to store the index.yaml.

**Additional context**
n/a

**Comment by neeraj-laad** [comment] 2019-07-25 12:23
duplicate of #63

**Closed by neeraj-laad** 2019-07-25 12:23 UTC
Labels: enhancement
