### ISSUE TITLE
java-spring-boot2 build errors on changes to LivenessEndpoint on Windows

### ISSUE THREAD

**Issue by tnixa** [appsody/stacks#373] opened 2019-09-23 15:29 UTC
**Describe the bug**
After running I make a valid change to the LivenessEndpoint and save the changes and I get a Build Error

**To Reproduce**
1. `mkdir java-spring-boot2`
2. `cd java-spring-boot2`
3. `appsody init java-spring-boot2`
4. `appsody run`
5. hit the `http://localhost:8080/actuator/liveness` endpoint which returns `{"status":"UP"}`
6. open file `C:\Users\appsody\projects092319\java-spring-boot2\src\main\java\application\LivenessEndpoint.java` in notepad and change line 28 to be... `
return "{\"test status\":\"UP\"}"; ` then save the file

**Expected behavior**
Expecting the build to pass and the endpoint text to change

**Actual behaviour**
```
[Container] Running: /project/java-spring-boot2-build.sh recompile
[Container] [0;34mCompile project in the foreground[0m
[Container] [0;32m> mvn compile[0m
[Container] [[1;34mINFO[m] Scanning for projects...
[Container] [[1;34mINFO[m]
[Container] [[1;34mINFO[m] [1m----------------------< [0;36mdev.appsody:application[0;1m >-----------------------[m
[Container] [[1;34mINFO[m] [1mBuilding application 0.0.1-SNAPSHOT[m
[Container] [[1;34mINFO[m] [1m--------------------------------[ jar ]---------------------------------[m
[Container] [[1;34mINFO[m]
[Container] [[1;34mINFO[m] [1m--- [0;32mmaven-resources-plugin:3.1.0:resources[m [1m(default-resources)[m @ [36mapplication[0;1m ---[m
[Container] [[1;34mINFO[m] Using 'UTF-8' encoding to copy filtered resources.
[Container] [[1;34mINFO[m] Copying 2 resources
[Container] [[1;34mINFO[m]
[Container] [[1;34mINFO[m] [1m--- [0;32mmaven-compiler-plugin:3.8.1:compile[m [1m(default-compile)[m @ [36mapplication[0;1m ---[m
[Container] [[1;34mINFO[m] Changes detected - recompiling the module!
[Container] [[1;34mINFO[m] Compiling 2 source files to /project/user-app/target/classes
[Container] [[1;34mINFO[m] -------------------------------------------------------------
[Container] [[1;31mERROR[m] COMPILATION ERROR :
[Container] [[1;34mINFO[m] -------------------------------------------------------------
[Container] [[1;31mERROR[m] /project/user-app/src/main/java/application/LivenessEndpoint.java:[1,1] illegal character: '\ufeff'
[Container] [[1;31mERROR[m] /project/user-app/src/main/java/application/LivenessEndpoint.java:[15,9] class, interface, or enum expected
[Container] [[1;34mINFO[m] 2 errors
[Container] [[1;34mINFO[m] -------------------------------------------------------------
[Container] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[Container] [[1;34mINFO[m] [1;31mBUILD FAILURE[m
[Container] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[Container] [[1;34mINFO[m] Total time:  5.286 s
[Container] [[1;34mINFO[m] Finished at: 2019-09-23T15:13:58Z
[Container] [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[Container] [[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile[m [1m(default-compile)[m on project [36mapplication[m: [1;31mCompilation failure[m: Compilation failure:
[Container] [[1;31mERROR[m] /project/user-app/src/main/java/application/LivenessEndpoint.java:[1,1] illegal character: '\ufeff'
[Container] [[1;31mERROR[m] /project/user-app/src/main/java/application/LivenessEndpoint.java:[15,9] class, interface, or enum expected
[Container] [[1;31mERROR[m] -> [1m[Help 1][m
[Container] [[1;31mERROR[m]
[Container] [[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[Container] [[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[Container] [[1;31mERROR[m]
[Container] [[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[Container] [[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[Container] Wait received error:exit status 1
[Container] Wait received error exit status 1
```
See attached `log.txt` for full console log
[log.txt](https://github.com/appsody/stacks/files/3642877/log.txt)

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**If applicable please specify:**
 - CLI version: 0.4.5
 - Stack you are using: java-spring-boot2

**Additional context**
I tried the same scenario on my mac and it works fine.

**Comment by ebullient** [comment] 2019-09-23 18:43
I am wondering if this is just timing. We need to know which version of the Spring stack? Changes were made to how rebuilds were triggered in v0.3.13, so I need to know if this was experienced before or after that.

I've made changes similar to this several times w/o seeing this issue. So the next question is.. if you make another change, does the error resolve itself?

**Comment by tnixa** [comment] 2019-09-24 13:22
I found this in the log..
`Installing parent dev.appsody:spring-boot2-stack:0.3.13`
I also tried making another change and I still get the same build error

**Comment by BarDweller** [comment] 2019-09-25 18:23
This shouldn't be timing related.. the trigger kicked in... and a recompile was started.. but the java compiler said your file was no good.. 

```[Container] [�[1;31mERROR�[m] /project/user-app/src/main/java/application/LivenessEndpoint.java:[1,1] illegal character: '\ufeff'
[Container] [�[1;31mERROR�[m] /project/user-app/src/main/java/application/LivenessEndpoint.java:[15,9] class, interface, or enum expected
```

A quick google on this suggests it's a [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) mostly caused by your save settings in notepad. 

It's not really a stack issue, as java doesn't support BOM's within UTF8 encoded source files. Recommended fix is to use an editor other than Notepad (notepad++, vscode, editplus, etc)

**Comment by tnixa** [comment] 2019-09-26 17:37
Scenario works fine using notepad++

**Comment by BarDweller** [comment] 2019-10-04 13:35
We can't fix this, using Notepad in this manner isn't compatible with Java, it's not up to the stack to make sure the .java files are actually valid for compiling. 

@neeraj-laad please close as wont fix or not a bug.. whichever is most appropriate

**Closed** 2019-10-04 15:46 UTC
Labels: bug
